# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - errorlint
    - copyloopvar
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - perfsprint
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
